# Generated by Django 2.2.12 on 2021-03-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesorias',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
