# Generated by Django 2.2.12 on 2021-03-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carreer', models.CharField(max_length=20)),
                ('instructor', models.TextField()),
                ('correo', models.TextField()),
                ('active', models.BooleanField()),
            ],
        ),
    ]
