# Generated by Django 2.2.12 on 2021-03-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
