# Generated by Django 3.1.4 on 2021-03-09 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0002_auto_20210309_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinador',
            name='carrera',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carreras.carrera'),
        ),
        migrations.AlterField(
            model_name='coordinador',
            name='coordinador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carreras.instructor'),
        ),
    ]
