# Generated by Django 2.2.12 on 2021-03-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('dateOn', models.DateField()),
                ('dateOff', models.DateField()),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
    ]
